# Generated by Django 5.0.8 on 2026-02-06 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_poems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poem',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='PoemMonthlyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField(db_index=True)),
                ('visits_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_visits', to='poems.poem')),
            ],
            options={
                'indexes': [models.Index(fields=['month_start', '-visits_count'], name='poem_month_visits_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='poemmonthlyvisit',
            constraint=models.UniqueConstraint(fields=('poem', 'month_start'), name='uniq_poem_monthly_visit'),
        ),
    ]
