from django.urls import path

from .views import (
    DashboardAuthChangePasswordView,
    DashboardAuthForgotPasswordView,
    DashboardAuthLoginView,
    DashboardAuthLogoutView,
    DashboardAuthMeView,
    DashboardAuthorDetailView,
    DashboardAuthorHardDeleteView,
    DashboardAuthorListCreateView,
    DashboardAuthorPoemsView,
    DashboardAuthorRestoreView,
    DashboardEmployeeDetailView,
    DashboardEmployeeHardDeleteView,
    DashboardEmployeeListCreateView,
    DashboardEmployeeResetPasswordView,
    DashboardEmployeeRestoreView,
    DashboardHomeView,
    DashboardPoemDetailView,
    DashboardPoemHardDeleteView,
    DashboardPoemListCreateView,
    DashboardPoemRestoreView,
    DashboardRoleDetailView,
    DashboardRoleHardDeleteView,
    DashboardRoleListCreateView,
    DashboardRoleRestoreView,
    DashboardSiteSettingsView,
)

urlpatterns = [
    path('dashboard/auth/login', DashboardAuthLoginView.as_view(), name='dashboard-auth-login'),
    path('dashboard/auth/logout', DashboardAuthLogoutView.as_view(), name='dashboard-auth-logout'),
    path('dashboard/auth/me', DashboardAuthMeView.as_view(), name='dashboard-auth-me'),
    path('dashboard/auth/forgot-password', DashboardAuthForgotPasswordView.as_view(), name='dashboard-auth-forgot'),
    path('dashboard/auth/change-password', DashboardAuthChangePasswordView.as_view(), name='dashboard-auth-change-password'),
    path('dashboard/home', DashboardHomeView.as_view(), name='dashboard-home'),
    path('dashboard/authors', DashboardAuthorListCreateView.as_view(), name='dashboard-authors'),
    path('dashboard/authors/<int:pk>', DashboardAuthorDetailView.as_view(), name='dashboard-author-detail'),
    path('dashboard/authors/<int:pk>/poems', DashboardAuthorPoemsView.as_view(), name='dashboard-author-poems'),
    path('dashboard/authors/<int:pk>/restore', DashboardAuthorRestoreView.as_view(), name='dashboard-author-restore'),
    path(
        'dashboard/authors/<int:pk>/hard-delete',
        DashboardAuthorHardDeleteView.as_view(),
        name='dashboard-author-hard-delete',
    ),
    path('dashboard/poems', DashboardPoemListCreateView.as_view(), name='dashboard-poems'),
    path('dashboard/poems/<int:pk>', DashboardPoemDetailView.as_view(), name='dashboard-poem-detail'),
    path('dashboard/poems/<int:pk>/restore', DashboardPoemRestoreView.as_view(), name='dashboard-poem-restore'),
    path('dashboard/poems/<int:pk>/hard-delete', DashboardPoemHardDeleteView.as_view(), name='dashboard-poem-hard-delete'),
    path('dashboard/employees', DashboardEmployeeListCreateView.as_view(), name='dashboard-employees'),
    path('dashboard/employees/<int:pk>', DashboardEmployeeDetailView.as_view(), name='dashboard-employee-detail'),
    path('dashboard/employees/<int:pk>/restore', DashboardEmployeeRestoreView.as_view(), name='dashboard-employee-restore'),
    path(
        'dashboard/employees/<int:pk>/hard-delete',
        DashboardEmployeeHardDeleteView.as_view(),
        name='dashboard-employee-hard-delete',
    ),
    path(
        'dashboard/employees/<int:pk>/reset-password',
        DashboardEmployeeResetPasswordView.as_view(),
        name='dashboard-employee-reset-password',
    ),
    path('dashboard/roles', DashboardRoleListCreateView.as_view(), name='dashboard-roles'),
    path('dashboard/roles/<int:pk>', DashboardRoleDetailView.as_view(), name='dashboard-role-detail'),
    path('dashboard/roles/<int:pk>/restore', DashboardRoleRestoreView.as_view(), name='dashboard-role-restore'),
    path('dashboard/roles/<int:pk>/hard-delete', DashboardRoleHardDeleteView.as_view(), name='dashboard-role-hard-delete'),
    path('dashboard/site-settings', DashboardSiteSettingsView.as_view(), name='dashboard-site-settings'),
]
